# config/packages/framework.yaml
framework:
  secret: "%env(APP_SECRET)%"
  session:
    handler_id: ~
when@test:
  framework:
    test: true
    session:
      storage_factory_id: session.storage.factory.mock_file
