imports:
  - php

filter:
  excluded_paths: [vendor/*, test/*]

build:
  image: default-bionic

  nodes:
    my-tests:
      environment:
        php:
          version: 8.3.3
      tests:
        override:
          # Xóa cache và tạo schema test SQLite trước khi chạy PHPUnit
          - php bin/console cache:clear --env=test
          - php bin/console doctrine:schema:create --env=test

          # Chạy PHPUnit mà không tạo coverage để tránh memory crash
          - composer phpunit -- --no-coverage

    analysis:
      environment:
        php:
          version: 8.3.3
      tests:
        override:
          # Låt Scrutinizer göra sin egen analys (kodstil, komplexitet m.m.)
          - php-scrutinizer-run

          # Kör även din lokala PHPStan med din config
          - command: "composer phpstan"
